runmode: debug
name: apiserver
addr: :8080
url: http://127.0.0.1
max_ping_count: 9
gormlog: true
jwt_secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5

tls:
  addr: :8081
  cert: conf/server.crt
  key: conf/server.key

logger:
  maxsize: 1M
  maxage: 5
  maxbackups: 5
  localtime: true
  compress: true
  logformat: console

db:
  username: zhuzi
  password: 123456
  addr: 127.0.0.1:3306
  dbname: db_apiserver
